### ISSUE TITLE
我遇到了一些问题，请求帮助

### ISSUE THREAD

**Issue by LIUYellowBlack** [Lemonace/PIER_code#3]
根据Run Env: python3 + tf1.5，我使用了tensorflow1.5+python3.6，我遇上了一些问题，请问能否给我一些建议

第一个疑惑：
DATA_MODE=1中的文件['/users/meituan_sxw/Downloads/part-r-00046']，请问这一美团文件是无法公开的么？同理，还有TRAIN_MODE=2中的文件avito_v1_new和TRAIN_MODE=4中的文件data

第二个问题：pier_model中的main.py，calculate_result(result_generator)报错
报错内容为下：
Traceback (most recent call last):
  File "D:\biyelunwen\PIER_code-main\rerank_paper\pier_model\main.py", line 114, in <module>
    calculate_result(result_generator)
  File "D:\biyelunwen\PIER_code-main\rerank_paper\pier_model\main.py", line 64, in calculate_result
    ctr_auc, ctr_auc_jp, ctr_cb, ctr_cb_jp = metrics.roc_auc_score(y_ctr, pred_ctr), metrics.roc_auc_score(y_ctr, ctr), np.sum(pred_ctr) / np.sum(y_ctr),  np.sum(ctr) / np.sum(y_ctr)
  File "C:\Users\Lenovo\anaconda3\envs\python3+tensorflow1.5\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "C:\Users\Lenovo\anaconda3\envs\python3+tensorflow1.5\lib\site-packages\sklearn\metrics\_ranking.py", line 523, in roc_auc_score
    y_true = check_array(y_true, ensure_2d=False, dtype=None)
  File "C:\Users\Lenovo\anaconda3\envs\python3+tensorflow1.5\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "C:\Users\Lenovo\anaconda3\envs\python3+tensorflow1.5\lib\site-packages\sklearn\utils\validation.py", line 729, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0,)) while a minimum of 1 is required.

该报错是说，无法读取数据的问题，下述是config.py中，我文件路径表示，其中只有DATA_MODE更改了，其余跟原件一样
if DATA_MODE == 1:
    TRAIN_FILE = ['/users/meituan_sxw/Downloads/part-r-00046']
    VALID_FILE = TRAIN_FILE
    PREDICT_FILE = VALID_FILE
    TEST_FILE = PREDICT_FILE
elif DATA_MODE == 2:
    TRAIN_FILE = ['/mnt/dolphinfs/hdd_pool/docker/user/hadoop-hmart-waimaiad/yangfan129/train_data/avito_v1_new/avito_v1_new/test_data/part-r-*']
    VALID_FILE = TRAIN_FILE
    TEST_FILE = VALID_FILE
elif DATA_MODE == 3:
    TRAIN_FILE = ["D://biyelunwen//PIER_code-main//avito_v3_new//avito_v3_new//train_data//part-r-*"]
    VALID_FILE = ["D://biyelunwen//PIER_code-main//avito_v3_new//avito_v3_new//test_data//part-r-*"]
    TEST_FILE= ["D://biyelunwen//PIER_code-main//avito_v3_new//avito_v3_new//test_data//part-r-*"]
elif DATA_MODE == 4:
    DATA_FILE = "/home/hadoop-hmart-waimaiad/cephfs/data/yangfan129/train_data/tfrecord-multi-channel-v1/"
    #TRAIN_LIST = ["20211222", "20211223", "20211224", "20211225"]
    TRAIN_LIST = ["20220123"]
    VALID_LIST = ["20220124"]
    TRAIN_FILE = [DATA_FILE + x + "/part-r-*" for x in TRAIN_LIST]
    VALID_FILE = [DATA_FILE + x + "/part-r-0001*" for x in VALID_LIST]
    TEST_FILE = [DATA_FILE + x + "/part-r-00011" for x in TRAIN_LIST]

**Comment by LIUYellowBlack** [comment]
wo shi sb

**Comment by Lemonace** [comment]
sorry 之前收到你发的邮件，回你可能没收到。现在还有问题吗
